source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'rails', '~> 7.0.4'
gem 'sqlite3'
gem 'puma', '~> 5.0'
gem 'twilio-ruby'
gem 'httparty'
gem 'sidekiq'
gem 'redis'
gem 'bootstrap', '~> 5.1.0'
gem 'jquery-rails'

group :development, :test do
  gem 'debug'
end